### PR TITLE
Job system

### PR DESCRIPTION
**Pull request by hannesnisula**
A (hopefully entirely) standalone job system that can be used by providing a job function and job data to a queue that will then be executed efficiently in parallel with other jobs.

# Features
- **Job priorities (low, medium, high)**
  Perhaps not even useful, to be decided.
- **Using fibers to enable switching jobs within jobs**
  This is to simplify usage of job dependencies.
- **Lock-free implementation to avoid possible stalls**

# Tasks
- [x] Job queue
- [ ] Queue test program
- [x] Fiber pool and usage
- [ ] Execution of job
- [ ] Data structure for paused jobs
- [ ] Handling of paused jobs
- [ ] Job test program

### CODE REVIEW

**Comment by theMoonwalker** [comment]
WTF is this???

**Comment by hannesnisula** [comment]
> 
> 
> WTF is this???

Now listen here you little shit

**Comment by hannesnisula** [comment]
## Queue
The current solution for an MPMC queue did not consider batch pushing and the mechanic does not support this well.
I find two viable ways of handling this, right now:
1. Simply loop the single push.
2. Construct a simple locked queue.
I am going for option **#1** and to temporarily swap to a locked queue would be trivial.

## Fibers
After considering some kind of "MPMC" lock-free free list for fibers it was clear that it would be so similar to the underlying mechanic of the queue so the queue will be used for the fibers as well.

**Comment by hannesnisula** [comment]
Trying out different methods of handling the project.
I split this up and is now closing this.

**Pull request closed without merging**
